# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.grant import Grant
from activityinfo.client.models.user_role import UserRole
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AddUserRequest(BaseModel):
    """
    AddUserRequest
    """ # noqa: E501
    email: StrictStr = Field(description="The email of the user to add")
    name: StrictStr = Field(description="The name of the user to add. This is only used in the email invitation to the user if there is no existing ActivityInfo account with this email address.")
    locale: StrictStr = Field(description="The locale to use when sending an email invite to the user, expressed as the two-letter ISO 639-1 code for the language, e.g. 'en' for English.")
    role: UserRole = Field(description="The role to assign to the user.")
    grants: Optional[List[Grant]] = Field(default=None, description="Additional permissions to grant to the user.")
    __properties: ClassVar[List[str]] = ["email", "name", "locale", "role", "grants"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddUserRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of role
        if self.role:
            _dict['role'] = self.role.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in grants (list)
        _items = []
        if self.grants:
            for _item_grants in self.grants:
                if _item_grants:
                    _items.append(_item_grants.to_dict())
            _dict['grants'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddUserRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "name": obj.get("name"),
            "locale": obj.get("locale"),
            "role": UserRole.from_dict(obj["role"]) if obj.get("role") is not None else None,
            "grants": [Grant.from_dict(_item) for _item in obj["grants"]] if obj.get("grants") is not None else None
        })
        return _obj


