# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AuditDatabaseRequest(BaseModel):
    """
    AuditDatabaseRequest
    """ # noqa: E501
    resource_filter: Optional[StrictStr] = Field(default=None, description="The id of a form, folder, or report. If provided, the result will only include events that relate to this resource.", alias="resourceFilter")
    type_filter: Optional[List[StrictStr]] = Field(default=None, description="Only include events of the given types.", alias="typeFilter")
    start_time: StrictInt = Field(description="The start time of the request, in milliseconds since the unix epoch. The results will include the first 100 - 150 events that occurred before this time.", alias="startTime")
    end_time: Optional[StrictInt] = Field(default=None, description="The end time of the request, in milliseconds since the unix epoch. The results will include the events that occurred after the end time and before the start time.", alias="endTime")
    __properties: ClassVar[List[str]] = ["resourceFilter", "typeFilter", "startTime", "endTime"]

    @field_validator('type_filter')
    def type_filter_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['RECORD', 'FORM', 'REPORT', 'FOLDER', 'DATABASE', 'LOCK', 'USER_PERMISSION', 'ROLE', 'AUTOMATION']):
                raise ValueError("each list item must be one of ('RECORD', 'FORM', 'REPORT', 'FOLDER', 'DATABASE', 'LOCK', 'USER_PERMISSION', 'ROLE', 'AUTOMATION')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuditDatabaseRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuditDatabaseRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resourceFilter": obj.get("resourceFilter"),
            "typeFilter": obj.get("typeFilter"),
            "startTime": obj.get("startTime"),
            "endTime": obj.get("endTime")
        })
        return _obj


