# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.database_role_filter import DatabaseRoleFilter
from activityinfo.client.models.database_role_parameter import DatabaseRoleParameter
from activityinfo.client.models.grant import Grant
from activityinfo.client.models.permission import Permission
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DatabaseRole(BaseModel):
    """
    DatabaseRole
    """ # noqa: E501
    id: StrictStr = Field(description="This role's id")
    label: StrictStr = Field(description="This role's human-readable label")
    permissions: Optional[List[Permission]] = Field(default=None, description="Permissions granted this role. Applicable for legacy roles, for grant based roles it will be limited to permissions that are NOT related to resources, like MANAGE_USERS, MANAGE_ROLES")
    parameters: Optional[List[DatabaseRoleParameter]] = Field(default=None, description="Parameters defined for this role. Parameters can be referenced in filtering formulas.")
    filters: Optional[List[DatabaseRoleFilter]] = Field(default=None, description="Pre-defined filters. Role filters allow other users to choose filters for permissions without having to write formulas themselves. -- NOTEWORTHY - only used by legacy roles")
    grants: Optional[List[Grant]] = None
    version: Optional[StrictInt] = 0
    grant_based: Optional[StrictBool] = Field(default=True, alias="grantBased")
    __properties: ClassVar[List[str]] = ["id", "label", "permissions", "parameters", "filters", "grants", "version", "grantBased"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatabaseRole from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in permissions (list)
        _items = []
        if self.permissions:
            for _item_permissions in self.permissions:
                if _item_permissions:
                    _items.append(_item_permissions.to_dict())
            _dict['permissions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in parameters (list)
        _items = []
        if self.parameters:
            for _item_parameters in self.parameters:
                if _item_parameters:
                    _items.append(_item_parameters.to_dict())
            _dict['parameters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in grants (list)
        _items = []
        if self.grants:
            for _item_grants in self.grants:
                if _item_grants:
                    _items.append(_item_grants.to_dict())
            _dict['grants'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatabaseRole from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "label": obj.get("label"),
            "permissions": [Permission.from_dict(_item) for _item in obj["permissions"]] if obj.get("permissions") is not None else None,
            "parameters": [DatabaseRoleParameter.from_dict(_item) for _item in obj["parameters"]] if obj.get("parameters") is not None else None,
            "filters": [DatabaseRoleFilter.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "grants": [Grant.from_dict(_item) for _item in obj["grants"]] if obj.get("grants") is not None else None,
            "version": obj.get("version") if obj.get("version") is not None else 0,
            "grantBased": obj.get("grantBased") if obj.get("grantBased") is not None else True
        })
        return _obj


