# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DatabaseResource(BaseModel):
    """
    A resource (folder, form or subform) that belongs to a database
    """ # noqa: E501
    id: StrictStr = Field(description="The resource's id. Form and subform resources must have globally-unique ids (across all of ActivityInfo) but folder ids are only guaranteed to be unique within a single database.")
    type: Optional[StrictStr] = Field(default=None, description="The resource type. Values: DATABASE, FOLDER, REPORT, FORM, SUB_FORM")
    parent_id: Optional[StrictStr] = Field(default=None, description="The id of this resource's parent, for example, a folder id. If this is a top-level folder or form, then the parentId will be the id of the database itself.", alias="parentId")
    label: Optional[StrictStr] = Field(default=None, description="The resource's human-readable label.")
    visibility: Optional[StrictStr] = Field(default=None, description="The resource's visibility. Values: PUBLIC, PRIVATE, REFERENCE")
    icon: Optional[StrictStr] = Field(default=None, description="Icon for the resource.")
    __properties: ClassVar[List[str]] = ["id", "type", "parentId", "label", "visibility", "icon"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DATABASE', 'FOLDER', 'REPORT', 'FORM', 'SUB_FORM']):
            raise ValueError("must be one of enum values ('DATABASE', 'FOLDER', 'REPORT', 'FORM', 'SUB_FORM')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatabaseResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of visibility
        if self.visibility:
            _dict['visibility'] = self.visibility.to_dict()
        # set to None if visibility (nullable) is None
        # and model_fields_set contains the field
        if self.visibility is None and "visibility" in self.model_fields_set:
            _dict['visibility'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatabaseResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "parentId": obj.get("parentId"),
            "label": obj.get("label"),
            "visibility": AnyOf.from_dict(obj["visibility"]) if obj.get("visibility") is not None else None,
            "icon": obj.get("icon")
        })
        return _obj


