# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from client.models.database_role import DatabaseRole
from client.models.grant import Grant
from client.models.owner_ref import OwnerRef
from client.models.resource import Resource
from client.models.role import Role
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DatabaseTree(BaseModel):
    """
    DatabaseTree
    """ # noqa: E501
    database_id: StrictStr = Field(alias="databaseId")
    user_id: StrictStr = Field(alias="userId")
    version: StrictStr
    label: StrictStr
    description: Optional[StrictStr] = None
    owner_ref: OwnerRef = Field(alias="ownerRef")
    language: StrictStr
    original_language: Optional[StrictStr] = Field(default=None, alias="originalLanguage")
    languages: Optional[List[Optional[StrictStr]]] = None
    role: DatabaseRole
    suspended: StrictBool
    billing_plan: Optional[StrictStr] = Field(default=None, alias="billingPlan")
    storage: StrictStr
    published_template: StrictBool = Field(alias="publishedTemplate")
    resources: List[Resource]
    grants: List[Grant]
    locks: Optional[List[Any]] = None
    roles: List[Role]
    security_categories: List[Dict[str, StrictStr]] = Field(alias="securityCategories")
    __properties: ClassVar[List[str]] = ["databaseId", "userId", "version", "label", "description", "ownerRef", "language", "originalLanguage", "languages", "role", "suspended", "billingPlan", "storage", "publishedTemplate", "resources", "grants", "locks", "roles", "securityCategories"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatabaseTree from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner_ref
        if self.owner_ref:
            _dict['ownerRef'] = self.owner_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of role
        if self.role:
            _dict['role'] = self.role.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in resources (list)
        _items = []
        if self.resources:
            for _item_resources in self.resources:
                if _item_resources:
                    _items.append(_item_resources.to_dict())
            _dict['resources'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in grants (list)
        _items = []
        if self.grants:
            for _item_grants in self.grants:
                if _item_grants:
                    _items.append(_item_grants.to_dict())
            _dict['grants'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in roles (list)
        _items = []
        if self.roles:
            for _item_roles in self.roles:
                if _item_roles:
                    _items.append(_item_roles.to_dict())
            _dict['roles'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if original_language (nullable) is None
        # and model_fields_set contains the field
        if self.original_language is None and "original_language" in self.model_fields_set:
            _dict['originalLanguage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatabaseTree from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "databaseId": obj.get("databaseId"),
            "userId": obj.get("userId"),
            "version": obj.get("version"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "ownerRef": OwnerRef.from_dict(obj["ownerRef"]) if obj.get("ownerRef") is not None else None,
            "language": obj.get("language"),
            "originalLanguage": obj.get("originalLanguage"),
            "languages": obj.get("languages"),
            "role": DatabaseRole.from_dict(obj["role"]) if obj.get("role") is not None else None,
            "suspended": obj.get("suspended"),
            "billingPlan": obj.get("billingPlan"),
            "storage": obj.get("storage"),
            "publishedTemplate": obj.get("publishedTemplate"),
            "resources": [Resource.from_dict(_item) for _item in obj["resources"]] if obj.get("resources") is not None else None,
            "grants": [Grant.from_dict(_item) for _item in obj["grants"]] if obj.get("grants") is not None else None,
            "locks": obj.get("locks"),
            "roles": [Role.from_dict(_item) for _item in obj["roles"]] if obj.get("roles") is not None else None,
            "securityCategories": obj.get("securityCategories")
        })
        return _obj


