# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.database_automation_action import DatabaseAutomationAction
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DatabaseAutomation(BaseModel):
    """
    DatabaseAutomation
    """ # noqa: E501
    automation_id: StrictStr = Field(description="The automation's id", alias="automationId")
    label: Optional[StrictStr] = Field(default=None, description="A human-readable label for this automation")
    resource_id: Optional[StrictStr] = Field(default=None, description="The resource (form, or subform) to which this automation applies.", alias="resourceId")
    trigger: Optional[StrictStr] = Field(default=None, description="The trigger that applies to this automation. Values: RECORD_ADDED, RECORD_EDITED, RECORD_DELETED")
    trigger_formula: Optional[StrictStr] = Field(default=None, description="The formula to which this automation applies. currently not supported", alias="triggerFormula")
    action: Optional[DatabaseAutomationAction] = Field(default=None, description="The action to be performed by this automation")
    active: Optional[StrictBool] = Field(default=None, description="Determines whether this automation is active or not")
    __properties: ClassVar[List[str]] = ["automationId", "label", "resourceId", "trigger", "triggerFormula", "action", "active"]

    @field_validator('trigger')
    def trigger_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['RECORD_ADDED', 'RECORD_EDITED', 'RECORD_DELETED']):
            raise ValueError("must be one of enum values ('RECORD_ADDED', 'RECORD_EDITED', 'RECORD_DELETED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatabaseAutomation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of action
        if self.action:
            _dict['action'] = self.action.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatabaseAutomation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "automationId": obj.get("automationId"),
            "label": obj.get("label"),
            "resourceId": obj.get("resourceId"),
            "trigger": obj.get("trigger"),
            "triggerFormula": obj.get("triggerFormula"),
            "action": DatabaseAutomationAction.from_dict(obj["action"]) if obj.get("action") is not None else None,
            "active": obj.get("active")
        })
        return _obj


