# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.database_lock_date_range import DatabaseLockDateRange
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DatabaseLock(BaseModel):
    """
    A record lock that has been defined for a database
    """ # noqa: E501
    id: StrictStr = Field(description="This lock's id.")
    label: StrictStr = Field(description="A human-readable label for this lock")
    resource_id: StrictStr = Field(description="The resource (database, folder, form, or subform) to which this lock applies.", alias="resourceId")
    date_range: Optional[DatabaseLockDateRange] = Field(default=None, description="The date range to which this lock applies, if it is a date-range lock.", alias="dateRange")
    formula: Optional[StrictStr] = Field(default=None, description="The formula to which this lock applies, if it is a rule-based lock.")
    message: Optional[StrictStr] = Field(default=None, description="user description of the rule-based lock.")
    deactivated: StrictBool = Field(description="Whether or not this lock is active. True when deactivated")
    __properties: ClassVar[List[str]] = ["id", "label", "resourceId", "dateRange", "formula", "message", "deactivated"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatabaseLock from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of date_range
        if self.date_range:
            _dict['dateRange'] = self.date_range.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatabaseLock from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "label": obj.get("label"),
            "resourceId": obj.get("resourceId"),
            "dateRange": DatabaseLockDateRange.from_dict(obj["dateRange"]) if obj.get("dateRange") is not None else None,
            "formula": obj.get("formula"),
            "message": obj.get("message"),
            "deactivated": obj.get("deactivated") if obj.get("deactivated") is not None else False
        })
        return _obj


