# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.database_automation import DatabaseAutomation
from activityinfo.client.models.record_ref import RecordRef
from activityinfo.client.models.user_ref import UserRef
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DatabaseAuditEvents(BaseModel):
    """
    DatabaseAuditEvents
    """ # noqa: E501
    id: StrictStr = Field(description="An opaque, id uniquely identifying this event within this result set.")
    time: StrictInt = Field(description="The time of this event, in seconds since 1970-01-01.")
    user: Optional[UserRef] = Field(default=None, description="The user who initiated this event.")
    record_ref: Optional[RecordRef] = Field(default=None, description="The record ref, if this event concerns a record.", alias="recordRef")
    form_id: Optional[StrictStr] = Field(default=None, description="The form id, if this event concerns a form.", alias="formId")
    version: Optional[StrictInt] = Field(default=None, description="The version number of the affected resource.")
    database_user_id: Optional[StrictStr] = Field(default=None, description="For user permission events, this is the id of the user who was affected.", alias="databaseUserId")
    description: StrictStr = Field(description="A human-readable description of the event.")
    type: List[StrictStr] = Field(description="The type of event. Values: DATABASE_TREE, USER, RECORD, FORM, AUTOMATION")
    resource_types: List[Optional[StrictStr]] = Field(description="One or more type(s) of the resource(s) affected", alias="resourceTypes")
    resource_id: StrictStr = Field(description="Id of the affected resource OR id of the database if more than one resource type is present", alias="resourceId")
    added: StrictBool = Field(description="True if this event concerns an addition.")
    updated: StrictBool = Field(description="True if this event concerns an update.")
    deleted: StrictBool = Field(description="True if this event concerns an deletion.")
    recovered: StrictBool = Field(description="True if this event concerns a recovery of data.")
    reverted: StrictBool = Field(description="True if this event has been reverted by an administrator.")
    automation: Optional[DatabaseAutomation] = Field(default=None, description="The automation, if this event concerns an automation.")
    merge_id: Optional[StrictStr] = Field(default=None, description="The merge id, if this event concerns a merge of records.", alias="mergeId")
    __properties: ClassVar[List[str]] = ["id", "time", "user", "recordRef", "formId", "version", "databaseUserId", "description", "type", "resourceTypes", "resourceId", "added", "updated", "deleted", "recovered", "reverted", "automation", "mergeId"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['DATABASE_TREE', 'USER', 'RECORD', 'FORM', 'AUTOMATION']):
                raise ValueError("each list item must be one of ('DATABASE_TREE', 'USER', 'RECORD', 'FORM', 'AUTOMATION')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatabaseAuditEvents from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of record_ref
        if self.record_ref:
            _dict['recordRef'] = self.record_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in resource_types (list)
        _items = []
        if self.resource_types:
            for _item_resource_types in self.resource_types:
                if _item_resource_types:
                    _items.append(_item_resource_types.to_dict())
            _dict['resourceTypes'] = _items
        # override the default output from pydantic by calling `to_dict()` of automation
        if self.automation:
            _dict['automation'] = self.automation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatabaseAuditEvents from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "time": obj.get("time"),
            "user": UserRef.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "recordRef": RecordRef.from_dict(obj["recordRef"]) if obj.get("recordRef") is not None else None,
            "formId": obj.get("formId"),
            "version": obj.get("version"),
            "databaseUserId": obj.get("databaseUserId"),
            "description": obj.get("description"),
            "type": obj.get("type"),
            "resourceTypes": [AnyOf.from_dict(_item) for _item in obj["resourceTypes"]] if obj.get("resourceTypes") is not None else None,
            "resourceId": obj.get("resourceId"),
            "added": obj.get("added"),
            "updated": obj.get("updated"),
            "deleted": obj.get("deleted"),
            "recovered": obj.get("recovered"),
            "reverted": obj.get("reverted"),
            "automation": DatabaseAutomation.from_dict(obj["automation"]) if obj.get("automation") is not None else None,
            "mergeId": obj.get("mergeId")
        })
        return _obj


