# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from client.models.field_type_parameters_items_update_dto import FieldTypeParametersItemsUpdateDTO
from client.models.type_parameter_lookup_config import TypeParameterLookupConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FieldTypeParametersUpdateDTO(BaseModel):
    """
    FieldTypeParametersUpdateDTO
    """ # noqa: E501
    units: Optional[StrictStr] = None
    input_mask: Optional[StrictStr] = Field(default=None, alias="inputMask")
    barcode: Optional[StrictBool] = None
    cardinality: Optional[StrictStr] = None
    range: Optional[List[Dict[str, StrictStr]]] = None
    form_id: Optional[StrictStr] = Field(default=None, alias="formId")
    items: Optional[List[FieldTypeParametersItemsUpdateDTO]] = None
    formula: Optional[StrictStr] = None
    prefix_formula: Optional[StrictStr] = Field(default=None, alias="prefixFormula")
    lookup_configs: Optional[List[TypeParameterLookupConfig]] = Field(default=None, alias="lookupConfigs")
    aggregation: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["units", "inputMask", "barcode", "cardinality", "range", "formId", "items", "formula", "prefixFormula", "lookupConfigs", "aggregation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FieldTypeParametersUpdateDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in lookup_configs (list)
        _items = []
        if self.lookup_configs:
            for _item_lookup_configs in self.lookup_configs:
                if _item_lookup_configs:
                    _items.append(_item_lookup_configs.to_dict())
            _dict['lookupConfigs'] = _items
        # set to None if units (nullable) is None
        # and model_fields_set contains the field
        if self.units is None and "units" in self.model_fields_set:
            _dict['units'] = None

        # set to None if input_mask (nullable) is None
        # and model_fields_set contains the field
        if self.input_mask is None and "input_mask" in self.model_fields_set:
            _dict['inputMask'] = None

        # set to None if barcode (nullable) is None
        # and model_fields_set contains the field
        if self.barcode is None and "barcode" in self.model_fields_set:
            _dict['barcode'] = None

        # set to None if cardinality (nullable) is None
        # and model_fields_set contains the field
        if self.cardinality is None and "cardinality" in self.model_fields_set:
            _dict['cardinality'] = None

        # set to None if range (nullable) is None
        # and model_fields_set contains the field
        if self.range is None and "range" in self.model_fields_set:
            _dict['range'] = None

        # set to None if form_id (nullable) is None
        # and model_fields_set contains the field
        if self.form_id is None and "form_id" in self.model_fields_set:
            _dict['formId'] = None

        # set to None if items (nullable) is None
        # and model_fields_set contains the field
        if self.items is None and "items" in self.model_fields_set:
            _dict['items'] = None

        # set to None if formula (nullable) is None
        # and model_fields_set contains the field
        if self.formula is None and "formula" in self.model_fields_set:
            _dict['formula'] = None

        # set to None if prefix_formula (nullable) is None
        # and model_fields_set contains the field
        if self.prefix_formula is None and "prefix_formula" in self.model_fields_set:
            _dict['prefixFormula'] = None

        # set to None if lookup_configs (nullable) is None
        # and model_fields_set contains the field
        if self.lookup_configs is None and "lookup_configs" in self.model_fields_set:
            _dict['lookupConfigs'] = None

        # set to None if aggregation (nullable) is None
        # and model_fields_set contains the field
        if self.aggregation is None and "aggregation" in self.model_fields_set:
            _dict['aggregation'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FieldTypeParametersUpdateDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "units": obj.get("units"),
            "inputMask": obj.get("inputMask"),
            "barcode": obj.get("barcode"),
            "cardinality": obj.get("cardinality"),
            "range": obj.get("range"),
            "formId": obj.get("formId"),
            "items": [FieldTypeParametersItemsUpdateDTO.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "formula": obj.get("formula"),
            "prefixFormula": obj.get("prefixFormula"),
            "lookupConfigs": [TypeParameterLookupConfig.from_dict(_item) for _item in obj["lookupConfigs"]] if obj.get("lookupConfigs") is not None else None,
            "aggregation": obj.get("aggregation")
        })
        return _obj


