# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.form_schema_element_parameter import FormSchemaElementParameter
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FormSchemaElement(BaseModel):
    """
    FormSchemaElement
    """ # noqa: E501
    id: StrictStr = Field(description="An immutable CUID for this field that is unique within the form")
    code: Optional[StrictStr] = Field(default=None, description="A developer-friendly code for this field that can be used in formulas and in the API. Must match the pattern ^[A-Za-z][A-Za-z0-9_]*")
    label: StrictStr = Field(description="A short human-friendly label for this field")
    description: Optional[StrictStr] = Field(default=None, description="An optional more detailed sub-label for this field")
    relevance_condition: Optional[StrictStr] = Field(default=None, description="A boolean-valued ActivityInfo formula that determines when this field is 'relevant'. Fields that are not relevant are not displayed during data entry and must be blank.", alias="relevanceCondition")
    validation_condition: Optional[StrictStr] = Field(default=None, description="A boolean-valued ActivityInfo formula that determines when this field's value is valid.", alias="validationCondition")
    data_entry_visible: Optional[StrictBool] = Field(default=True, description="If false, this field is not shown in data entry", alias="dataEntryVisible")
    table_visible: Optional[StrictBool] = Field(default=True, description="If false, this field is not shown by default in the table view", alias="tableVisible")
    required: StrictBool = Field(description="If true, a value for this field must be provided")
    key: StrictBool = Field(description="If true, this field is part of the form's natural key fields whose combination must be unique within the form")
    unique: Optional[StrictBool] = Field(default=False, description="If true, the value for this field must be unique across the form's records")
    read_only: Optional[StrictBool] = Field(default=False, description="If true, the value for this field cannot be modified by any user (but it can be set by default on record add).", alias="readOnly")
    default_value: Optional[StrictStr] = Field(default=None, description="The default value for this field, set on record add", alias="defaultValue")
    default_value_formula: Optional[StrictStr] = Field(default=None, description="An ActivityInfo formula that generates the default value for this field, set on record add", alias="defaultValueFormula")
    type: StrictStr = Field(description="The field type.")
    security_category_id: Optional[StrictStr] = Field(default=None, alias="securityCategoryId")
    type_parameters: Optional[FormSchemaElementParameter] = Field(default=None, description="Additional type-specific properties of this field.", alias="typeParameters")
    __properties: ClassVar[List[str]] = ["id", "code", "label", "description", "relevanceCondition", "validationCondition", "dataEntryVisible", "tableVisible", "required", "key", "unique", "readOnly", "defaultValue", "defaultValueFormula", "type", "securityCategoryId", "typeParameters"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['serial', 'month', 'attachment', 'geopoint', 'FREE_TEXT', 'quantity', 'enumerated', 'multiselectreference', 'epiweek', 'subform', 'date', 'calculated', 'reversereference', 'reference', 'fortnight', 'section', 'NARRATIVE']):
            raise ValueError("must be one of enum values ('serial', 'month', 'attachment', 'geopoint', 'FREE_TEXT', 'quantity', 'enumerated', 'multiselectreference', 'epiweek', 'subform', 'date', 'calculated', 'reversereference', 'reference', 'fortnight', 'section', 'NARRATIVE')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FormSchemaElement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of type_parameters
        if self.type_parameters:
            _dict['typeParameters'] = self.type_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FormSchemaElement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "code": obj.get("code"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "relevanceCondition": obj.get("relevanceCondition"),
            "validationCondition": obj.get("validationCondition"),
            "dataEntryVisible": obj.get("dataEntryVisible") if obj.get("dataEntryVisible") is not None else True,
            "tableVisible": obj.get("tableVisible") if obj.get("tableVisible") is not None else True,
            "required": obj.get("required") if obj.get("required") is not None else False,
            "key": obj.get("key") if obj.get("key") is not None else False,
            "unique": obj.get("unique") if obj.get("unique") is not None else False,
            "readOnly": obj.get("readOnly") if obj.get("readOnly") is not None else False,
            "defaultValue": obj.get("defaultValue"),
            "defaultValueFormula": obj.get("defaultValueFormula"),
            "type": obj.get("type"),
            "securityCategoryId": obj.get("securityCategoryId"),
            "typeParameters": FormSchemaElementParameter.from_dict(obj["typeParameters"]) if obj.get("typeParameters") is not None else None
        })
        return _obj


