# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.form_schema_element_parameter_lookup import FormSchemaElementParameterLookup
from activityinfo.client.models.form_schema_element_parameter_translation import FormSchemaElementParameterTranslation
from activityinfo.client.models.form_schema_element_parameter_value import FormSchemaElementParameterValue
from activityinfo.client.models.range_inner import RangeInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FormSchemaElementParameter(BaseModel):
    """
    FormSchemaElementParameter
    """ # noqa: E501
    prefix_formula: Optional[StrictStr] = Field(default=None, description="For fields of type 'serial', provides a formula that will be used to compute the prefix of the generated serial number.", alias="prefixFormula")
    digits: Optional[StrictInt] = Field(default=None, description="For fields of type 'serial', indicates how many digits long the generated serial number will be")
    units: Optional[StrictStr] = Field(default=None, description="For fields of type 'quantity', describes the units of the quantity")
    aggregation: Optional[StrictStr] = Field(default=None, description="For fields of type 'quantity', describes the aggregation method e.g. 'sum'. Not currently used(?)")
    input_mask: Optional[StrictStr] = Field(default=None, description="For fields of type 'FREE_TEXT' (user type 'Text' or 'Barcode'), provides a pattern-based input mask", alias="inputMask")
    barcode: Optional[StrictBool] = Field(default=None, description="For fields of type 'FREE_TEXT' (user type 'Text' or 'Barcode'), true when field is barcode")
    formula: Optional[StrictStr] = Field(default=None, description="For fields of type 'calculated', provides the formula for the field's value")
    cardinality: Optional[StrictStr] = Field(default=None, description="For fields of type 'enumerated' (user type 'Single selection' or 'Multiple selection'), indicates whether single or multiple select")
    values: Optional[List[FormSchemaElementParameterValue]] = Field(default=None, description="For fields of type 'enumerated' (user type 'Single selection' or 'Multiple selection'), provided the list of valid choices")
    presentation: Optional[StrictStr] = Field(default=None, description="For fields of type 'enumerated' (user type 'Single selection' or 'Multiple selection'), indicate whether shown as dropdown or not. Only relevant for multiple selection, i.e. where cardinality: multiple")
    range: Optional[List[RangeInner]] = Field(default=None, description="For fields of type 'reference' or 'multiselectreference' (user type 'Reference', 'User', or 'Multiple Reference'), provides the id of the form that this field references. For 'User', this reference is '{dbid}@users'.")
    lookup_configs: Optional[List[FormSchemaElementParameterLookup]] = Field(default=None, description="For fields of type 'reference', specifies the lookup configuration for the field.", alias="lookupConfigs")
    form_id: Optional[StrictStr] = Field(default=None, description="For fields of type 'subform' and 'reversereference', provides the id of the form/subform that this field references", alias="formId")
    field_id: Optional[StrictStr] = Field(default=None, description="For fields of type 'reversereference', provides the id of the reference field on the form that this field references", alias="fieldId")
    capture_methods: Optional[List[StrictStr]] = Field(default=None, description="For fields of type 'attachment', indicates which types of attachments can be added.", alias="captureMethods")
    required_accuracy: Optional[StrictInt] = Field(default=None, description="For fields of type 'geopoint', indicates the accuracy required when automatically specifying location.", alias="requiredAccuracy")
    manual_entry_allowed: Optional[StrictBool] = Field(default=None, description="For fields of type 'geopoint', true when manual entry of location is allowed.", alias="manualEntryAllowed")
    indentation_level: Optional[StrictInt] = Field(default=None, description="For fields of type 'section', indicates the level of indentation of the heading.", alias="indentationLevel")
    translation_config: Optional[FormSchemaElementParameterTranslation] = Field(default=None, description="For fields of type 'FREE_TEXT', 'NARRATIVE' or 'calculated', the translation config specifies which other field this is a translation of, and into which language.", alias="translationConfig")
    __properties: ClassVar[List[str]] = ["prefixFormula", "digits", "units", "aggregation", "inputMask", "barcode", "formula", "cardinality", "values", "presentation", "range", "lookupConfigs", "formId", "fieldId", "captureMethods", "requiredAccuracy", "manualEntryAllowed", "indentationLevel", "translationConfig"]

    @field_validator('presentation')
    def presentation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['automatic', 'dropdown']):
            raise ValueError("must be one of enum values ('automatic', 'dropdown')")
        return value

    @field_validator('capture_methods')
    def capture_methods_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['CAMERA', 'SIGNATURE', 'FILE']):
                raise ValueError("each list item must be one of ('CAMERA', 'SIGNATURE', 'FILE')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FormSchemaElementParameter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cardinality
        if self.cardinality:
            _dict['cardinality'] = self.cardinality.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in values (list)
        _items = []
        if self.values:
            for _item_values in self.values:
                if _item_values:
                    _items.append(_item_values.to_dict())
            _dict['values'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in range (list)
        _items = []
        if self.range:
            for _item_range in self.range:
                if _item_range:
                    _items.append(_item_range.to_dict())
            _dict['range'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in lookup_configs (list)
        _items = []
        if self.lookup_configs:
            for _item_lookup_configs in self.lookup_configs:
                if _item_lookup_configs:
                    _items.append(_item_lookup_configs.to_dict())
            _dict['lookupConfigs'] = _items
        # override the default output from pydantic by calling `to_dict()` of translation_config
        if self.translation_config:
            _dict['translationConfig'] = self.translation_config.to_dict()
        # set to None if cardinality (nullable) is None
        # and model_fields_set contains the field
        if self.cardinality is None and "cardinality" in self.model_fields_set:
            _dict['cardinality'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FormSchemaElementParameter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prefixFormula": obj.get("prefixFormula"),
            "digits": obj.get("digits"),
            "units": obj.get("units"),
            "aggregation": obj.get("aggregation"),
            "inputMask": obj.get("inputMask"),
            "barcode": obj.get("barcode"),
            "formula": obj.get("formula"),
            "cardinality": AnyOf.from_dict(obj["cardinality"]) if obj.get("cardinality") is not None else None,
            "values": [FormSchemaElementParameterValue.from_dict(_item) for _item in obj["values"]] if obj.get("values") is not None else None,
            "presentation": obj.get("presentation"),
            "range": [RangeInner.from_dict(_item) for _item in obj["range"]] if obj.get("range") is not None else None,
            "lookupConfigs": [FormSchemaElementParameterLookup.from_dict(_item) for _item in obj["lookupConfigs"]] if obj.get("lookupConfigs") is not None else None,
            "formId": obj.get("formId"),
            "fieldId": obj.get("fieldId"),
            "captureMethods": obj.get("captureMethods"),
            "requiredAccuracy": obj.get("requiredAccuracy"),
            "manualEntryAllowed": obj.get("manualEntryAllowed"),
            "indentationLevel": obj.get("indentationLevel"),
            "translationConfig": FormSchemaElementParameterTranslation.from_dict(obj["translationConfig"]) if obj.get("translationConfig") is not None else None
        })
        return _obj


