# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.database_lock import DatabaseLock
from activityinfo.client.models.field_condition import FieldCondition
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FormPermissions(BaseModel):
    """
    FormPermissions
    """ # noqa: E501
    view: StrictBool
    view_filter: Optional[StrictStr] = Field(default=None, alias="viewFilter")
    create_record: StrictBool = Field(alias="createRecord")
    create_filter: Optional[StrictStr] = Field(default=None, alias="createFilter")
    edit_record: StrictBool = Field(alias="editRecord")
    edit_filter: Optional[StrictStr] = Field(default=None, alias="editFilter")
    delete_record: StrictBool = Field(alias="deleteRecord")
    delete_filter: Optional[StrictStr] = Field(default=None, alias="deleteFilter")
    bulk_delete: Optional[StrictBool] = Field(default=None, alias="bulkDelete")
    export_records: Optional[StrictBool] = Field(default=None, alias="exportRecords")
    resolve_duplicates: Optional[StrictBool] = Field(default=None, alias="resolveDuplicates")
    manage_import_configs: Optional[StrictBool] = Field(default=None, alias="manageImportConfigs")
    update_schema: Optional[StrictBool] = Field(default=None, alias="updateSchema")
    collection_links: Optional[StrictBool] = Field(default=None, alias="collectionLinks")
    public_form: Optional[StrictBool] = Field(default=None, alias="publicForm")
    api: Optional[StrictBool] = None
    security_categories: Optional[List[StrictStr]] = Field(default=None, alias="securityCategories")
    locks: Optional[List[DatabaseLock]] = None
    field_level_conditions: Optional[List[FieldCondition]] = Field(default=None, alias="fieldLevelConditions")
    __properties: ClassVar[List[str]] = ["view", "viewFilter", "createRecord", "createFilter", "editRecord", "editFilter", "deleteRecord", "deleteFilter", "bulkDelete", "exportRecords", "resolveDuplicates", "manageImportConfigs", "updateSchema", "collectionLinks", "publicForm", "api", "securityCategories", "locks", "fieldLevelConditions"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FormPermissions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in locks (list)
        _items = []
        if self.locks:
            for _item_locks in self.locks:
                if _item_locks:
                    _items.append(_item_locks.to_dict())
            _dict['locks'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in field_level_conditions (list)
        _items = []
        if self.field_level_conditions:
            for _item_field_level_conditions in self.field_level_conditions:
                if _item_field_level_conditions:
                    _items.append(_item_field_level_conditions.to_dict())
            _dict['fieldLevelConditions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FormPermissions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "view": obj.get("view"),
            "viewFilter": obj.get("viewFilter"),
            "createRecord": obj.get("createRecord"),
            "createFilter": obj.get("createFilter"),
            "editRecord": obj.get("editRecord"),
            "editFilter": obj.get("editFilter"),
            "deleteRecord": obj.get("deleteRecord"),
            "deleteFilter": obj.get("deleteFilter"),
            "bulkDelete": obj.get("bulkDelete"),
            "exportRecords": obj.get("exportRecords"),
            "resolveDuplicates": obj.get("resolveDuplicates"),
            "manageImportConfigs": obj.get("manageImportConfigs"),
            "updateSchema": obj.get("updateSchema"),
            "collectionLinks": obj.get("collectionLinks"),
            "publicForm": obj.get("publicForm"),
            "api": obj.get("api"),
            "securityCategories": obj.get("securityCategories"),
            "locks": [DatabaseLock.from_dict(_item) for _item in obj["locks"]] if obj.get("locks") is not None else None,
            "fieldLevelConditions": [FieldCondition.from_dict(_item) for _item in obj["fieldLevelConditions"]] if obj.get("fieldLevelConditions") is not None else None
        })
        return _obj


