# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from client.models.schema_field_dto import SchemaFieldDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FormSchema(BaseModel):
    """
    FormSchema
    """ # noqa: E501
    id: StrictStr
    schema_version: StrictInt = Field(alias="schemaVersion")
    database_id: StrictStr = Field(alias="databaseId")
    parent_form_id: Optional[StrictStr] = Field(default=None, alias="parentFormId")
    label: StrictStr
    record_label_field_id: Optional[StrictStr] = Field(default=None, alias="recordLabelFieldId")
    elements: List[SchemaFieldDTO]
    __properties: ClassVar[List[str]] = ["id", "schemaVersion", "databaseId", "parentFormId", "label", "recordLabelFieldId", "elements"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FormSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in elements (list)
        _items = []
        if self.elements:
            for _item_elements in self.elements:
                if _item_elements:
                    _items.append(_item_elements.to_dict())
            _dict['elements'] = _items
        # set to None if parent_form_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_form_id is None and "parent_form_id" in self.model_fields_set:
            _dict['parentFormId'] = None

        # set to None if record_label_field_id (nullable) is None
        # and model_fields_set contains the field
        if self.record_label_field_id is None and "record_label_field_id" in self.model_fields_set:
            _dict['recordLabelFieldId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FormSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "schemaVersion": obj.get("schemaVersion"),
            "databaseId": obj.get("databaseId"),
            "parentFormId": obj.get("parentFormId"),
            "label": obj.get("label"),
            "recordLabelFieldId": obj.get("recordLabelFieldId"),
            "elements": [SchemaFieldDTO.from_dict(_item) for _item in obj["elements"]] if obj.get("elements") is not None else None
        })
        return _obj


