# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetDatabasesResponse(BaseModel):
    """
    GetDatabasesResponse
    """ # noqa: E501
    database_id: StrictStr = Field(description="The globally-unique id of this database.", alias="databaseId")
    label: StrictStr = Field(description="The human-readable name of this database.")
    description: Optional[StrictStr] = Field(default=None, description="A longer, optional description for this database.")
    owner_id: Optional[StrictStr] = Field(default=None, description="The id of the user who owns this database.", alias="ownerId")
    billing_account_id: Optional[StrictInt] = Field(default=None, description="The id of the billing account to which this database belongs", alias="billingAccountId")
    suspended: Optional[StrictBool] = Field(default=None, description="True if this database belongs to a billing account that has been suspended.")
    published_template: Optional[StrictBool] = Field(default=None, description="True if this database has been published as a template.", alias="publishedTemplate")
    languages: Optional[List[StrictStr]] = Field(default=None, description="The list of languages that have been defined for this database, including the original language, if set, and any translations.")
    __properties: ClassVar[List[str]] = ["databaseId", "label", "description", "ownerId", "billingAccountId", "suspended", "publishedTemplate", "languages"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetDatabasesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetDatabasesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "databaseId": obj.get("databaseId"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "ownerId": obj.get("ownerId"),
            "billingAccountId": obj.get("billingAccountId"),
            "suspended": obj.get("suspended"),
            "publishedTemplate": obj.get("publishedTemplate"),
            "languages": obj.get("languages")
        })
        return _obj


