# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Permission(BaseModel):
    """
    An individual operation (add/edit/view) and any associated record-level condition, either associated with a Grant for a specific database resource, or assigned to a role directly for higher-level database operations.
    """ # noqa: E501
    operation: StrictStr = Field(description="One of a number of predetermined values")
    filter: Optional[StrictStr] = Field(default=None, description="A formula which restricts a permission to specific records. Only record-level permissions can be filtered.")
    security_categories: Optional[List[StrictStr]] = Field(default=None, description="The security categories that have been defined for this permission.", alias="securityCategories")
    __properties: ClassVar[List[str]] = ["operation", "filter", "securityCategories"]

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['VIEW', 'DISCOVER', 'ADD_RECORD', 'EDIT_RECORD', 'MANAGE_REFERENCE_DATA', 'DELETE_RECORD', 'BULK_DELETE', 'EXPORT_RECORDS', 'MANAGE_USERS', 'LOCK_RECORDS', 'ADD_RESOURCE', 'EDIT_RESOURCE', 'DELETE_RESOURCE', 'MANAGE_COLLECTION_LINKS', 'AUDIT', 'SHARE_REPORTS', 'PUBLISH_REPORTS', 'MANAGE_ROLES', 'MANAGE_AUTOMATIONS', 'MANAGE_TRANSLATIONS', 'RESOLVE_DUPLICATES', 'SHARE_VIEWS', 'MANAGE_IMPORT_CONFIGS', 'VIEW_FIELD', 'EDIT_FIELD']):
            raise ValueError("must be one of enum values ('VIEW', 'DISCOVER', 'ADD_RECORD', 'EDIT_RECORD', 'MANAGE_REFERENCE_DATA', 'DELETE_RECORD', 'BULK_DELETE', 'EXPORT_RECORDS', 'MANAGE_USERS', 'LOCK_RECORDS', 'ADD_RESOURCE', 'EDIT_RESOURCE', 'DELETE_RESOURCE', 'MANAGE_COLLECTION_LINKS', 'AUDIT', 'SHARE_REPORTS', 'PUBLISH_REPORTS', 'MANAGE_ROLES', 'MANAGE_AUTOMATIONS', 'MANAGE_TRANSLATIONS', 'RESOLVE_DUPLICATES', 'SHARE_VIEWS', 'MANAGE_IMPORT_CONFIGS', 'VIEW_FIELD', 'EDIT_FIELD')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Permission from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Permission from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": obj.get("operation"),
            "filter": obj.get("filter"),
            "securityCategories": obj.get("securityCategories")
        })
        return _obj


