# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.query_column import QueryColumn
from activityinfo.client.models.query_filter_set import QueryFilterSet
from activityinfo.client.models.query_sort import QuerySort
from activityinfo.client.models.query_source import QuerySource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QueryRowsRequest(BaseModel):
    """
    QueryRowsRequest
    """ # noqa: E501
    row_sources: List[QuerySource] = Field(description="Exactly one RowSource is required.", alias="rowSources")
    form_id: Optional[StrictStr] = Field(default=None, description="CUID of the root form to query. This is deprecated in favour of rowSources", alias="formId")
    columns: List[QueryColumn] = Field(description="The list of columns to retrieve")
    filter: Optional[StrictStr] = Field(default=None, description="A boolean-valued ActivityInfo formula to filter the records included in this query. Resulting rows must match both the filter formula, if provided, and all the provided filterSets. Filter sets are more efficient than formulas when you have a large number of values.")
    filter_sets: Optional[List[QueryFilterSet]] = Field(default=None, description="Set-based filters to apply to records returned by the query, each of which is a pair of a formula and a set of values to include. Resulting rows must match both the filter formula, if provided, and all the provided filterSets. Filter sets are more efficient than formulas when you have a large number of values.", alias="filterSets")
    sort: Optional[List[QuerySort]] = Field(default=None, description="Sort instructions specified with a formula and a direction. Only one sort instruction can be specified, so sorting on multiple columns must be done with a single formula expression.")
    truncate_strings: Optional[StrictBool] = Field(default=None, alias="truncateStrings")
    validation: Optional[Dict[str, Any]] = None
    drafts: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["rowSources", "formId", "columns", "filter", "filterSets", "sort", "truncateStrings", "validation", "drafts", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryRowsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in row_sources (list)
        _items = []
        if self.row_sources:
            for _item_row_sources in self.row_sources:
                if _item_row_sources:
                    _items.append(_item_row_sources.to_dict())
            _dict['rowSources'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in columns (list)
        _items = []
        if self.columns:
            for _item_columns in self.columns:
                if _item_columns:
                    _items.append(_item_columns.to_dict())
            _dict['columns'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in filter_sets (list)
        _items = []
        if self.filter_sets:
            for _item_filter_sets in self.filter_sets:
                if _item_filter_sets:
                    _items.append(_item_filter_sets.to_dict())
            _dict['filterSets'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sort (list)
        _items = []
        if self.sort:
            for _item_sort in self.sort:
                if _item_sort:
                    _items.append(_item_sort.to_dict())
            _dict['sort'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryRowsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rowSources": [QuerySource.from_dict(_item) for _item in obj["rowSources"]] if obj.get("rowSources") is not None else None,
            "formId": obj.get("formId"),
            "columns": [QueryColumn.from_dict(_item) for _item in obj["columns"]] if obj.get("columns") is not None else None,
            "filter": obj.get("filter"),
            "filterSets": [QueryFilterSet.from_dict(_item) for _item in obj["filterSets"]] if obj.get("filterSets") is not None else None,
            "sort": [QuerySort.from_dict(_item) for _item in obj["sort"]] if obj.get("sort") is not None else None,
            "truncateStrings": obj.get("truncateStrings"),
            "validation": obj.get("validation"),
            "drafts": obj.get("drafts"),
            "tags": obj.get("tags")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


