# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from client.models.field_type_parameters_update_dto import FieldTypeParametersUpdateDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SchemaFieldDTO(BaseModel):
    """
    SchemaFieldDTO
    """ # noqa: E501
    id: StrictStr
    code: Optional[StrictStr]
    label: StrictStr
    description: Optional[StrictStr] = None
    relevance_condition: Optional[StrictStr] = Field(default=None, alias="relevanceCondition")
    validation_condition: Optional[StrictStr] = Field(default=None, alias="validationCondition")
    data_entry_visible: Optional[StrictBool] = Field(default=True, alias="dataEntryVisible")
    table_visible: Optional[StrictBool] = Field(default=True, alias="tableVisible")
    required: StrictBool
    key: Optional[StrictBool] = None
    unique: Optional[StrictBool] = None
    read_only: Optional[StrictBool] = Field(default=None, alias="readOnly")
    default_value_formula: Optional[StrictStr] = Field(default=None, alias="defaultValueFormula")
    type: StrictStr
    type_parameters: Optional[FieldTypeParametersUpdateDTO] = Field(default=None, alias="typeParameters")
    __properties: ClassVar[List[str]] = ["id", "code", "label", "description", "relevanceCondition", "validationCondition", "dataEntryVisible", "tableVisible", "required", "key", "unique", "readOnly", "defaultValueFormula", "type", "typeParameters"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchemaFieldDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of type_parameters
        if self.type_parameters:
            _dict['typeParameters'] = self.type_parameters.to_dict()
        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if relevance_condition (nullable) is None
        # and model_fields_set contains the field
        if self.relevance_condition is None and "relevance_condition" in self.model_fields_set:
            _dict['relevanceCondition'] = None

        # set to None if validation_condition (nullable) is None
        # and model_fields_set contains the field
        if self.validation_condition is None and "validation_condition" in self.model_fields_set:
            _dict['validationCondition'] = None

        # set to None if key (nullable) is None
        # and model_fields_set contains the field
        if self.key is None and "key" in self.model_fields_set:
            _dict['key'] = None

        # set to None if unique (nullable) is None
        # and model_fields_set contains the field
        if self.unique is None and "unique" in self.model_fields_set:
            _dict['unique'] = None

        # set to None if read_only (nullable) is None
        # and model_fields_set contains the field
        if self.read_only is None and "read_only" in self.model_fields_set:
            _dict['readOnly'] = None

        # set to None if default_value_formula (nullable) is None
        # and model_fields_set contains the field
        if self.default_value_formula is None and "default_value_formula" in self.model_fields_set:
            _dict['defaultValueFormula'] = None

        # set to None if type_parameters (nullable) is None
        # and model_fields_set contains the field
        if self.type_parameters is None and "type_parameters" in self.model_fields_set:
            _dict['typeParameters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchemaFieldDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "code": obj.get("code"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "relevanceCondition": obj.get("relevanceCondition"),
            "validationCondition": obj.get("validationCondition"),
            "dataEntryVisible": obj.get("dataEntryVisible") if obj.get("dataEntryVisible") is not None else True,
            "tableVisible": obj.get("tableVisible") if obj.get("tableVisible") is not None else True,
            "required": obj.get("required"),
            "key": obj.get("key"),
            "unique": obj.get("unique"),
            "readOnly": obj.get("readOnly"),
            "defaultValueFormula": obj.get("defaultValueFormula"),
            "type": obj.get("type"),
            "typeParameters": FieldTypeParametersUpdateDTO.from_dict(obj["typeParameters"]) if obj.get("typeParameters") is not None else None
        })
        return _obj


