# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from activityinfo.client.models.database_lock import DatabaseLock
from activityinfo.client.models.database_resource import DatabaseResource
from activityinfo.client.models.database_role import DatabaseRole
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateDatabaseRequest(BaseModel):
    """
    UpdateDatabaseRequest
    """ # noqa: E501
    resource_updates: Optional[List[DatabaseResource]] = Field(default=None, description="List of resources to add or update.", alias="resourceUpdates")
    resource_deletions: Optional[List[StrictStr]] = Field(default=None, description="List of resource ids to delete from the database.", alias="resourceDeletions")
    lock_updates: Optional[List[DatabaseLock]] = Field(default=None, description="List of locks to add or update", alias="lockUpdates")
    lock_deletions: Optional[List[StrictStr]] = Field(default=None, description="List of lock ids to delete", alias="lockDeletions")
    role_updates: Optional[List[DatabaseRole]] = Field(default=None, description="List of roles to add or update", alias="roleUpdates")
    role_deletions: Optional[List[StrictStr]] = Field(default=None, description="List of role ids to delete", alias="roleDeletions")
    language_updates: Optional[List[StrictStr]] = Field(default=None, description="List of languages to add or update", alias="languageUpdates")
    language_deletions: Optional[List[StrictStr]] = Field(default=None, description="List of languages to delete", alias="languageDeletions")
    original_language: Optional[StrictStr] = Field(default=None, description="Original language update", alias="originalLanguage")
    __properties: ClassVar[List[str]] = ["resourceUpdates", "resourceDeletions", "lockUpdates", "lockDeletions", "roleUpdates", "roleDeletions", "languageUpdates", "languageDeletions", "originalLanguage"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateDatabaseRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in resource_updates (list)
        _items = []
        if self.resource_updates:
            for _item_resource_updates in self.resource_updates:
                if _item_resource_updates:
                    _items.append(_item_resource_updates.to_dict())
            _dict['resourceUpdates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in lock_updates (list)
        _items = []
        if self.lock_updates:
            for _item_lock_updates in self.lock_updates:
                if _item_lock_updates:
                    _items.append(_item_lock_updates.to_dict())
            _dict['lockUpdates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in role_updates (list)
        _items = []
        if self.role_updates:
            for _item_role_updates in self.role_updates:
                if _item_role_updates:
                    _items.append(_item_role_updates.to_dict())
            _dict['roleUpdates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateDatabaseRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resourceUpdates": [DatabaseResource.from_dict(_item) for _item in obj["resourceUpdates"]] if obj.get("resourceUpdates") is not None else None,
            "resourceDeletions": obj.get("resourceDeletions"),
            "lockUpdates": [DatabaseLock.from_dict(_item) for _item in obj["lockUpdates"]] if obj.get("lockUpdates") is not None else None,
            "lockDeletions": obj.get("lockDeletions"),
            "roleUpdates": [DatabaseRole.from_dict(_item) for _item in obj["roleUpdates"]] if obj.get("roleUpdates") is not None else None,
            "roleDeletions": obj.get("roleDeletions"),
            "languageUpdates": obj.get("languageUpdates"),
            "languageDeletions": obj.get("languageDeletions"),
            "originalLanguage": obj.get("originalLanguage")
        })
        return _obj


