# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserPreflightResponse(BaseModel):
    """
    UserPreflightResponse
    """ # noqa: E501
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    activation_status: StrictStr = Field(alias="activationStatus")
    name: StrictStr
    added_to_database: StrictBool = Field(alias="addedToDatabase")
    valid_email: StrictBool = Field(alias="validEmail")
    localized_error_message: Optional[StrictStr] = Field(default=None, alias="localizedErrorMessage")
    __properties: ClassVar[List[str]] = ["userId", "activationStatus", "name", "addedToDatabase", "validEmail", "localizedErrorMessage"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserPreflightResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['userId'] = None

        # set to None if localized_error_message (nullable) is None
        # and model_fields_set contains the field
        if self.localized_error_message is None and "localized_error_message" in self.model_fields_set:
            _dict['localizedErrorMessage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserPreflightResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "userId": obj.get("userId"),
            "activationStatus": obj.get("activationStatus"),
            "name": obj.get("name"),
            "addedToDatabase": obj.get("addedToDatabase"),
            "validEmail": obj.get("validEmail"),
            "localizedErrorMessage": obj.get("localizedErrorMessage")
        })
        return _obj


