# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from activityinfo.client.models.user_role import UserRole
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class User(BaseModel):
    """
    User
    """ # noqa: E501
    database_id: StrictStr = Field(alias="databaseId")
    user_id: StrictStr = Field(alias="userId")
    name: StrictStr = Field(description="The user's name, provided either when invited or by the user themselves after activating their account.")
    email: StrictStr = Field(description="This user's email address.")
    role: UserRole = Field(description="This user's assigned role in the database.")
    version: Optional[StrictInt] = Field(default=None, description="A monotonically-increasing version number. This version is incremented each time a change is made to the users permissions.")
    invite_date: Optional[date] = Field(default=None, description="The date on which the user was invited to this database.", alias="inviteDate")
    invite_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="inviteTime")
    delivery_status: Optional[StrictStr] = Field(default=None, alias="deliveryStatus")
    invite_accepted: Optional[StrictBool] = Field(default=None, description="True if the user has accepted the invitation to create an ActivityInfo account.", alias="inviteAccepted")
    locked: Optional[StrictBool] = Field(default=None, description="True if this user's account has been locked following too many failed authentication attempts.")
    user_license_type: Optional[StrictStr] = Field(default=None, description="The type of user license required for this user, in this database.", alias="userLicenseType")
    last_login_date: Optional[date] = Field(default=None, description="Date of last login on the platform.", alias="lastLoginDate")
    last_login_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="lastLoginTime")
    activation_status: Optional[StrictStr] = Field(default=None, description="The user's current account status.", alias="activationStatus")
    __properties: ClassVar[List[str]] = ["databaseId", "userId", "name", "email", "role", "version", "inviteDate", "inviteTime", "deliveryStatus", "inviteAccepted", "locked", "userLicenseType", "lastLoginDate", "lastLoginTime", "activationStatus"]

    @field_validator('delivery_status')
    def delivery_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['UNKNOWN', 'OK', 'HARD_BOUNCE', 'SPAM_COMPLAINT', 'MANUAL_SUPPRESSION']):
            raise ValueError("must be one of enum values ('UNKNOWN', 'OK', 'HARD_BOUNCE', 'SPAM_COMPLAINT', 'MANUAL_SUPPRESSION')")
        return value

    @field_validator('user_license_type')
    def user_license_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'BASIC', 'FULL']):
            raise ValueError("must be one of enum values ('NONE', 'BASIC', 'FULL')")
        return value

    @field_validator('activation_status')
    def activation_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NO_ACCOUNT', 'PENDING', 'ACTIVE', 'INACTIVE', 'CLOSED']):
            raise ValueError("must be one of enum values ('NO_ACCOUNT', 'PENDING', 'ACTIVE', 'INACTIVE', 'CLOSED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of role
        if self.role:
            _dict['role'] = self.role.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "databaseId": obj.get("databaseId"),
            "userId": obj.get("userId"),
            "name": obj.get("name"),
            "email": obj.get("email"),
            "role": UserRole.from_dict(obj["role"]) if obj.get("role") is not None else None,
            "version": obj.get("version"),
            "inviteDate": obj.get("inviteDate"),
            "inviteTime": obj.get("inviteTime"),
            "deliveryStatus": obj.get("deliveryStatus"),
            "inviteAccepted": obj.get("inviteAccepted"),
            "locked": obj.get("locked"),
            "userLicenseType": obj.get("userLicenseType"),
            "lastLoginDate": obj.get("lastLoginDate"),
            "lastLoginTime": obj.get("lastLoginTime"),
            "activationStatus": obj.get("activationStatus")
        })
        return _obj


