# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_database(self) -> None:
        """Test case for add_database

        Add Database
        """
        pass

    async def test_add_database_user(self) -> None:
        """Test case for add_database_user

        Add Database User
        """
        pass

    async def test_add_form(self) -> None:
        """Test case for add_form

        Add Form
        """
        pass

    async def test_audit_database(self) -> None:
        """Test case for audit_database

        Audit Database
        """
        pass

    async def test_delete_database(self) -> None:
        """Test case for delete_database

        Delete Database
        """
        pass

    async def test_delete_database_user(self) -> None:
        """Test case for delete_database_user

        Delete Database User
        """
        pass

    async def test_get_database_translations(self) -> None:
        """Test case for get_database_translations

        Get Database Translations
        """
        pass

    async def test_get_database_tree(self) -> None:
        """Test case for get_database_tree

        Get Database Tree
        """
        pass

    async def test_get_database_users(self) -> None:
        """Test case for get_database_users

        Get Database Users
        """
        pass

    async def test_get_form_records(self) -> None:
        """Test case for get_form_records

        Get Form Records
        """
        pass

    async def test_get_form_schema(self) -> None:
        """Test case for get_form_schema

        Get Form Schema
        """
        pass

    async def test_get_form_translations(self) -> None:
        """Test case for get_form_translations

        Get Form Translations
        """
        pass

    async def test_get_form_tree(self) -> None:
        """Test case for get_form_tree

        Get Form Tree
        """
        pass

    async def test_get_job_status(self) -> None:
        """Test case for get_job_status

        Get Job Status
        """
        pass

    async def test_get_user_databases(self) -> None:
        """Test case for get_user_databases

        Get User Databases
        """
        pass

    async def test_preflight_database_user(self) -> None:
        """Test case for preflight_database_user

        Preflight Database User
        """
        pass

    async def test_query_rows(self) -> None:
        """Test case for query_rows

        Query Rows
        """
        pass

    async def test_start_job(self) -> None:
        """Test case for start_job

        Start Job
        """
        pass

    async def test_update_database(self) -> None:
        """Test case for update_database

        Update Database
        """
        pass

    async def test_update_database_translations(self) -> None:
        """Test case for update_database_translations

        Update Database Translations
        """
        pass

    async def test_update_database_user_role(self) -> None:
        """Test case for update_database_user_role

        Update Database User Role
        """
        pass

    async def test_update_form_records(self) -> None:
        """Test case for update_form_records

        Update Form Records
        """
        pass

    async def test_update_form_schema(self) -> None:
        """Test case for update_form_schema

        Update Form Schema
        """
        pass

    async def test_update_form_schema_translations(self) -> None:
        """Test case for update_form_schema_translations

        Update Form Schema Translations
        """
        pass


if __name__ == '__main__':
    unittest.main()
