# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.database_lock import DatabaseLock

class TestDatabaseLock(unittest.TestCase):
    """DatabaseLock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseLock:
        """Test DatabaseLock
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseLock`
        """
        model = DatabaseLock()
        if include_optional:
            return DatabaseLock(
                id = '',
                label = '',
                resource_id = '',
                date_range = client.models.database_lock.DatabaseLock(
                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                formula = '',
                message = '',
                deactivated = True
            )
        else:
            return DatabaseLock(
                id = '',
                label = '',
                resource_id = '',
                deactivated = True,
        )
        """

    def testDatabaseLock(self):
        """Test DatabaseLock"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
