# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.add_update_form_response import AddUpdateFormResponse

class TestAddUpdateFormResponse(unittest.TestCase):
    """AddUpdateFormResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddUpdateFormResponse:
        """Test AddUpdateFormResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddUpdateFormResponse`
        """
        model = AddUpdateFormResponse()
        if include_optional:
            return AddUpdateFormResponse(
                database = client.models.database.Database(
                    database_id = '', 
                    user_id = '', 
                    version = '', 
                    label = '', 
                    description = '', 
                    owner_ref = null, 
                    language = '', 
                    original_language = '', 
                    languages = [
                        ''
                        ], 
                    suspended = True, 
                    role = null, 
                    roles = [
                        client.models.database_role.DatabaseRole(
                            id = '', 
                            label = '', 
                            permissions = [
                                client.models.permission.Permission(
                                    operation = '', 
                                    filter = '', 
                                    security_categories = [
                                        client.models.security_category.SecurityCategory(
                                            id = '', 
                                            label = '', )
                                        ], )
                                ], 
                            parameters = [
                                client.models.database_role_parameter.DatabaseRoleParameter(
                                    parameter_id = '', 
                                    label = '', 
                                    range = '', )
                                ], 
                            filters = [
                                client.models.database_role_filter.DatabaseRoleFilter(
                                    id = '', 
                                    label = '', 
                                    filter = '', )
                                ], 
                            grants = [
                                client.models.grant.Grant(
                                    resource_id = '', 
                                    optional = True, 
                                    operations = [
                                        client.models.permission.Permission(
                                            operation = '', 
                                            filter = '', 
                                            security_categories = [
                                                client.models.security_category.SecurityCategory(
                                                    id = '', 
                                                    label = '', )
                                                ], )
                                        ], 
                                    conditions = [
                                        client.models.field_condition.FieldCondition(
                                            operations = [
                                                ''
                                                ], 
                                            criteria = 'ALL', 
                                            rules = [
                                                client.models.field_condition_rule.FieldConditionRule(
                                                    object_type = '', 
                                                    predicate_type = '', 
                                                    value = '', )
                                                ], )
                                        ], )
                                ], 
                            version = 56, 
                            grant_based = True, )
                        ], 
                    storage = '', 
                    published_template = True, 
                    security_categories = [
                        
                        ], 
                    resources = [
                        client.models.database_resource.DatabaseResource(
                            id = '', 
                            type = 'DATABASE', 
                            parent_id = '', 
                            label = '', 
                            visibility = '', 
                            icon = '', )
                        ], 
                    locks = [
                        client.models.database_lock.DatabaseLock(
                            id = '', 
                            label = '', 
                            resource_id = '', 
                            date_range = null, 
                            formula = '', 
                            message = '', 
                            deactivated = True, )
                        ], 
                    grants = [
                        client.models.grant.Grant(
                            resource_id = '', 
                            optional = True, 
                            operations = [
                                
                                ], 
                            conditions = [
                                client.models.field_condition.FieldCondition(
                                    operations = [
                                        ''
                                        ], 
                                    criteria = 'ALL', 
                                    rules = [
                                        client.models.field_condition_rule.FieldConditionRule(
                                            object_type = '', 
                                            predicate_type = '', 
                                            value = '', )
                                        ], )
                                ], )
                        ], 
                    billing_account_id = '', 
                    billing_plan = '', ),
                forms = [
                    client.models.form.Form(
                        id = '', 
                        schema = null, 
                        schema_version = 56, 
                        permissions = null, 
                        visible = True, 
                        deleted = True, 
                        suspended = True, )
                    ]
            )
        else:
            return AddUpdateFormResponse(
                database = client.models.database.Database(
                    database_id = '', 
                    user_id = '', 
                    version = '', 
                    label = '', 
                    description = '', 
                    owner_ref = null, 
                    language = '', 
                    original_language = '', 
                    languages = [
                        ''
                        ], 
                    suspended = True, 
                    role = null, 
                    roles = [
                        client.models.database_role.DatabaseRole(
                            id = '', 
                            label = '', 
                            permissions = [
                                client.models.permission.Permission(
                                    operation = '', 
                                    filter = '', 
                                    security_categories = [
                                        client.models.security_category.SecurityCategory(
                                            id = '', 
                                            label = '', )
                                        ], )
                                ], 
                            parameters = [
                                client.models.database_role_parameter.DatabaseRoleParameter(
                                    parameter_id = '', 
                                    label = '', 
                                    range = '', )
                                ], 
                            filters = [
                                client.models.database_role_filter.DatabaseRoleFilter(
                                    id = '', 
                                    label = '', 
                                    filter = '', )
                                ], 
                            grants = [
                                client.models.grant.Grant(
                                    resource_id = '', 
                                    optional = True, 
                                    operations = [
                                        client.models.permission.Permission(
                                            operation = '', 
                                            filter = '', 
                                            security_categories = [
                                                client.models.security_category.SecurityCategory(
                                                    id = '', 
                                                    label = '', )
                                                ], )
                                        ], 
                                    conditions = [
                                        client.models.field_condition.FieldCondition(
                                            operations = [
                                                ''
                                                ], 
                                            criteria = 'ALL', 
                                            rules = [
                                                client.models.field_condition_rule.FieldConditionRule(
                                                    object_type = '', 
                                                    predicate_type = '', 
                                                    value = '', )
                                                ], )
                                        ], )
                                ], 
                            version = 56, 
                            grant_based = True, )
                        ], 
                    storage = '', 
                    published_template = True, 
                    security_categories = [
                        
                        ], 
                    resources = [
                        client.models.database_resource.DatabaseResource(
                            id = '', 
                            type = 'DATABASE', 
                            parent_id = '', 
                            label = '', 
                            visibility = '', 
                            icon = '', )
                        ], 
                    locks = [
                        client.models.database_lock.DatabaseLock(
                            id = '', 
                            label = '', 
                            resource_id = '', 
                            date_range = null, 
                            formula = '', 
                            message = '', 
                            deactivated = True, )
                        ], 
                    grants = [
                        client.models.grant.Grant(
                            resource_id = '', 
                            optional = True, 
                            operations = [
                                
                                ], 
                            conditions = [
                                client.models.field_condition.FieldCondition(
                                    operations = [
                                        ''
                                        ], 
                                    criteria = 'ALL', 
                                    rules = [
                                        client.models.field_condition_rule.FieldConditionRule(
                                            object_type = '', 
                                            predicate_type = '', 
                                            value = '', )
                                        ], )
                                ], )
                        ], 
                    billing_account_id = '', 
                    billing_plan = '', ),
                forms = [
                    client.models.form.Form(
                        id = '', 
                        schema = null, 
                        schema_version = 56, 
                        permissions = null, 
                        visible = True, 
                        deleted = True, 
                        suspended = True, )
                    ],
        )
        """

    def testAddUpdateFormResponse(self):
        """Test AddUpdateFormResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
