# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.form_schema_element import FormSchemaElement

class TestFormSchemaElement(unittest.TestCase):
    """FormSchemaElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormSchemaElement:
        """Test FormSchemaElement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormSchemaElement`
        """
        model = FormSchemaElement()
        if include_optional:
            return FormSchemaElement(
                id = '',
                code = '',
                label = '',
                description = '',
                relevance_condition = '',
                validation_condition = '',
                data_entry_visible = True,
                table_visible = True,
                required = True,
                key = True,
                unique = True,
                read_only = True,
                default_value = '',
                default_value_formula = '',
                type = '',
                security_category_id = '',
                type_parameters = client.models.form_schema_element_parameter.FormSchemaElementParameter(
                    prefix_formula = '', 
                    digits = 56, 
                    units = '', 
                    aggregation = '', 
                    input_mask = '', 
                    barcode = True, 
                    formula = '', 
                    cardinality = '', 
                    values = [
                        client.models.form_schema_element_parameter_value.FormSchemaElementParameterValue(
                            id = '', 
                            label = '', )
                        ], 
                    presentation = 'automatic', 
                    range = [
                        client.models.range_inner.Range_inner(
                            form_id = '', )
                        ], 
                    lookup_configs = [
                        client.models.form_schema_element_parameter_lookup.FormSchemaElementParameterLookup(
                            id = '', 
                            formula = '', 
                            lookup_label = '', )
                        ], 
                    form_id = '', 
                    field_id = '', 
                    capture_methods = [
                        'CAMERA'
                        ], 
                    required_accuracy = 56, 
                    manual_entry_allowed = True, 
                    indentation_level = 56, 
                    translation_config = null, )
            )
        else:
            return FormSchemaElement(
                id = '',
                label = '',
                required = True,
                key = True,
                type = '',
        )
        """

    def testFormSchemaElement(self):
        """Test FormSchemaElement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
