# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.grant import Grant

class TestGrant(unittest.TestCase):
    """Grant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Grant:
        """Test Grant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Grant`
        """
        model = Grant()
        if include_optional:
            return Grant(
                resource_id = '',
                optional = True,
                operations = [
                    client.models.permission.Permission(
                        operation = '', 
                        filter = '', 
                        security_categories = [
                            client.models.security_category.SecurityCategory(
                                id = '', 
                                label = '', )
                            ], )
                    ],
                conditions = [
                    client.models.field_condition.FieldCondition(
                        operations = [
                            ''
                            ], 
                        criteria = 'ALL', 
                        rules = [
                            client.models.field_condition_rule.FieldConditionRule(
                                object_type = '', 
                                predicate_type = '', 
                                value = '', )
                            ], )
                    ]
            )
        else:
            return Grant(
                resource_id = '',
                optional = True,
                operations = [
                    client.models.permission.Permission(
                        operation = '', 
                        filter = '', 
                        security_categories = [
                            client.models.security_category.SecurityCategory(
                                id = '', 
                                label = '', )
                            ], )
                    ],
        )
        """

    def testGrant(self):
        """Test Grant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
