# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.user import User

class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> User:
        """Test User
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `User`
        """
        model = User()
        if include_optional:
            return User(
                database_id = '',
                user_id = '',
                name = '',
                email = '',
                role = client.models.user_role.UserRole(
                    id = '', 
                    parameters = { }, 
                    resources = [
                        ''
                        ], ),
                version = 56,
                invite_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                invite_time = 1.337,
                delivery_status = '',
                invite_accepted = True,
                locked = True,
                user_license_type = '',
                last_login_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                last_login_time = 1.337,
                activation_status = ''
            )
        else:
            return User(
                database_id = '',
                user_id = '',
                name = '',
                email = '',
                role = client.models.user_role.UserRole(
                    id = '', 
                    parameters = { }, 
                    resources = [
                        ''
                        ], ),
        )
        """

    def testUser(self):
        """Test User"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
