# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.database_audit import DatabaseAudit

class TestDatabaseAudit(unittest.TestCase):
    """DatabaseAudit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseAudit:
        """Test DatabaseAudit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseAudit`
        """
        model = DatabaseAudit()
        if include_optional:
            return DatabaseAudit(
                events = [
                    client.models.database_audit_events.DatabaseAuditEvents(
                        id = '', 
                        time = 56, 
                        user = null, 
                        record_ref = null, 
                        form_id = '', 
                        version = 56, 
                        database_user_id = '', 
                        description = '', 
                        type = [
                            'DATABASE_TREE'
                            ], 
                        resource_types = [
                            ''
                            ], 
                        resource_id = '', 
                        added = True, 
                        updated = True, 
                        deleted = True, 
                        recovered = True, 
                        reverted = True, 
                        automation = null, 
                        merge_id = '', )
                    ],
                start_time = 56,
                end_time = 56,
                more_events = True
            )
        else:
            return DatabaseAudit(
                start_time = 56,
                end_time = 56,
                more_events = True,
        )
        """

    def testDatabaseAudit(self):
        """Test DatabaseAudit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
