# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.field_condition_rule import FieldConditionRule

class TestFieldConditionRule(unittest.TestCase):
    """FieldConditionRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldConditionRule:
        """Test FieldConditionRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldConditionRule`
        """
        model = FieldConditionRule()
        if include_optional:
            return FieldConditionRule(
                object_type = '',
                predicate_type = '',
                value = ''
            )
        else:
            return FieldConditionRule(
                object_type = '',
                predicate_type = '',
                value = '',
        )
        """

    def testFieldConditionRule(self):
        """Test FieldConditionRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
