# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.form_permissions import FormPermissions

class TestFormPermissions(unittest.TestCase):
    """FormPermissions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormPermissions:
        """Test FormPermissions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormPermissions`
        """
        model = FormPermissions()
        if include_optional:
            return FormPermissions(
                view = True,
                view_filter = '',
                create_record = True,
                create_filter = '',
                edit_record = True,
                edit_filter = '',
                delete_record = True,
                delete_filter = '',
                bulk_delete = True,
                export_records = True,
                resolve_duplicates = True,
                manage_import_configs = True,
                update_schema = True,
                collection_links = True,
                public_form = True,
                api = True,
                security_categories = [
                    ''
                    ],
                locks = [
                    client.models.database_lock.DatabaseLock(
                        id = '', 
                        label = '', 
                        resource_id = '', 
                        date_range = null, 
                        formula = '', 
                        message = '', 
                        deactivated = True, )
                    ],
                field_level_conditions = [
                    client.models.field_condition.FieldCondition(
                        operations = [
                            ''
                            ], 
                        criteria = 'ALL', 
                        rules = [
                            client.models.field_condition_rule.FieldConditionRule(
                                object_type = '', 
                                predicate_type = '', 
                                value = '', )
                            ], )
                    ]
            )
        else:
            return FormPermissions(
                view = True,
                create_record = True,
                edit_record = True,
                delete_record = True,
        )
        """

    def testFormPermissions(self):
        """Test FormPermissions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
