# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.database_automation import DatabaseAutomation

class TestDatabaseAutomation(unittest.TestCase):
    """DatabaseAutomation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseAutomation:
        """Test DatabaseAutomation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseAutomation`
        """
        model = DatabaseAutomation()
        if include_optional:
            return DatabaseAutomation(
                automation_id = '',
                label = '',
                resource_id = '',
                trigger = 'RECORD_ADDED',
                trigger_formula = '',
                action = client.models.database_automation_action.DatabaseAutomationAction(
                    type = '', 
                    url = '', ),
                active = True
            )
        else:
            return DatabaseAutomation(
                automation_id = '',
        )
        """

    def testDatabaseAutomation(self):
        """Test DatabaseAutomation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
