# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.update_database_request import UpdateDatabaseRequest

class TestUpdateDatabaseRequest(unittest.TestCase):
    """UpdateDatabaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateDatabaseRequest:
        """Test UpdateDatabaseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateDatabaseRequest`
        """
        model = UpdateDatabaseRequest()
        if include_optional:
            return UpdateDatabaseRequest(
                resource_updates = [
                    client.models.database_resource.DatabaseResource(
                        id = '', 
                        type = 'DATABASE', 
                        parent_id = '', 
                        label = '', 
                        visibility = '', 
                        icon = '', )
                    ],
                resource_deletions = [
                    ''
                    ],
                lock_updates = [
                    client.models.database_lock.DatabaseLock(
                        id = '', 
                        label = '', 
                        resource_id = '', 
                        date_range = null, 
                        formula = '', 
                        message = '', 
                        deactivated = True, )
                    ],
                lock_deletions = [
                    ''
                    ],
                role_updates = [
                    client.models.database_role.DatabaseRole(
                        id = '', 
                        label = '', 
                        permissions = [
                            client.models.permission.Permission(
                                operation = '', 
                                filter = '', 
                                security_categories = [
                                    client.models.security_category.SecurityCategory(
                                        id = '', 
                                        label = '', )
                                    ], )
                            ], 
                        parameters = [
                            client.models.database_role_parameter.DatabaseRoleParameter(
                                parameter_id = '', 
                                label = '', 
                                range = '', )
                            ], 
                        filters = [
                            client.models.database_role_filter.DatabaseRoleFilter(
                                id = '', 
                                label = '', 
                                filter = '', )
                            ], 
                        grants = [
                            client.models.grant.Grant(
                                resource_id = '', 
                                optional = True, 
                                operations = [
                                    client.models.permission.Permission(
                                        operation = '', 
                                        filter = '', 
                                        security_categories = [
                                            client.models.security_category.SecurityCategory(
                                                id = '', 
                                                label = '', )
                                            ], )
                                    ], 
                                conditions = [
                                    client.models.field_condition.FieldCondition(
                                        operations = [
                                            ''
                                            ], 
                                        criteria = 'ALL', 
                                        rules = [
                                            client.models.field_condition_rule.FieldConditionRule(
                                                object_type = '', 
                                                predicate_type = '', 
                                                value = '', )
                                            ], )
                                    ], )
                            ], 
                        version = 56, 
                        grant_based = True, )
                    ],
                role_deletions = [
                    ''
                    ],
                language_updates = [
                    ''
                    ],
                language_deletions = [
                    ''
                    ],
                original_language = ''
            )
        else:
            return UpdateDatabaseRequest(
        )
        """

    def testUpdateDatabaseRequest(self):
        """Test UpdateDatabaseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
