# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.audit_database_request import AuditDatabaseRequest

class TestAuditDatabaseRequest(unittest.TestCase):
    """AuditDatabaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditDatabaseRequest:
        """Test AuditDatabaseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditDatabaseRequest`
        """
        model = AuditDatabaseRequest()
        if include_optional:
            return AuditDatabaseRequest(
                resource_filter = '',
                type_filter = [
                    ''
                    ],
                start_time = 56,
                end_time = 56
            )
        else:
            return AuditDatabaseRequest(
                start_time = 56,
        )
        """

    def testAuditDatabaseRequest(self):
        """Test AuditDatabaseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
