# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.add_form_request import AddFormRequest

class TestAddFormRequest(unittest.TestCase):
    """AddFormRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddFormRequest:
        """Test AddFormRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddFormRequest`
        """
        model = AddFormRequest()
        if include_optional:
            return AddFormRequest(
                form_resource = client.models.database_resource.DatabaseResource(
                    id = '', 
                    type = 'DATABASE', 
                    parent_id = '', 
                    label = '', 
                    visibility = '', 
                    icon = '', ),
                form_class = client.models.form_schema.FormSchema(
                    id = '', 
                    label = '', 
                    schema_version = 56, 
                    database_id = '', 
                    parent_form_id = '', 
                    record_label_field_id = '', 
                    elements = [
                        client.models.form_schema_element.FormSchemaElement(
                            id = '', 
                            code = '', 
                            label = '', 
                            description = '', 
                            relevance_condition = '', 
                            validation_condition = '', 
                            data_entry_visible = True, 
                            table_visible = True, 
                            required = True, 
                            key = True, 
                            unique = True, 
                            read_only = True, 
                            default_value = '', 
                            default_value_formula = '', 
                            type = '', 
                            security_category_id = '', 
                            type_parameters = null, )
                        ], )
            )
        else:
            return AddFormRequest(
                form_resource = client.models.database_resource.DatabaseResource(
                    id = '', 
                    type = 'DATABASE', 
                    parent_id = '', 
                    label = '', 
                    visibility = '', 
                    icon = '', ),
                form_class = client.models.form_schema.FormSchema(
                    id = '', 
                    label = '', 
                    schema_version = 56, 
                    database_id = '', 
                    parent_form_id = '', 
                    record_label_field_id = '', 
                    elements = [
                        client.models.form_schema_element.FormSchemaElement(
                            id = '', 
                            code = '', 
                            label = '', 
                            description = '', 
                            relevance_condition = '', 
                            validation_condition = '', 
                            data_entry_visible = True, 
                            table_visible = True, 
                            required = True, 
                            key = True, 
                            unique = True, 
                            read_only = True, 
                            default_value = '', 
                            default_value_formula = '', 
                            type = '', 
                            security_category_id = '', 
                            type_parameters = null, )
                        ], ),
        )
        """

    def testAddFormRequest(self):
        """Test AddFormRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
