# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.translation_dictionary_id import TranslationDictionaryId

class TestTranslationDictionaryId(unittest.TestCase):
    """TranslationDictionaryId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranslationDictionaryId:
        """Test TranslationDictionaryId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranslationDictionaryId`
        """
        model = TranslationDictionaryId()
        if include_optional:
            return TranslationDictionaryId(
                database_id = '',
                dictionary_id = ''
            )
        else:
            return TranslationDictionaryId(
                database_id = '',
                dictionary_id = '',
        )
        """

    def testTranslationDictionaryId(self):
        """Test TranslationDictionaryId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
