# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.database_audit_events import DatabaseAuditEvents

class TestDatabaseAuditEvents(unittest.TestCase):
    """DatabaseAuditEvents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseAuditEvents:
        """Test DatabaseAuditEvents
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseAuditEvents`
        """
        model = DatabaseAuditEvents()
        if include_optional:
            return DatabaseAuditEvents(
                id = '',
                time = 56,
                user = client.models.user_ref.UserRef(
                    id = '', 
                    name = '', 
                    email = '', ),
                record_ref = client.models.record_ref.RecordRef(
                    form_id = '', 
                    record_id = '', ),
                form_id = '',
                version = 56,
                database_user_id = '',
                description = '',
                type = [
                    'DATABASE_TREE'
                    ],
                resource_types = [
                    ''
                    ],
                resource_id = '',
                added = True,
                updated = True,
                deleted = True,
                recovered = True,
                reverted = True,
                automation = client.models.database_automation.DatabaseAutomation(
                    automation_id = '', 
                    label = '', 
                    resource_id = '', 
                    trigger = 'RECORD_ADDED', 
                    trigger_formula = '', 
                    action = null, 
                    active = True, ),
                merge_id = ''
            )
        else:
            return DatabaseAuditEvents(
                id = '',
                time = 56,
                description = '',
                type = [
                    'DATABASE_TREE'
                    ],
                resource_types = [
                    ''
                    ],
                resource_id = '',
                added = True,
                updated = True,
                deleted = True,
                recovered = True,
                reverted = True,
        )
        """

    def testDatabaseAuditEvents(self):
        """Test DatabaseAuditEvents"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
