# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.query_rows_request import QueryRowsRequest

class TestQueryRowsRequest(unittest.TestCase):
    """QueryRowsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryRowsRequest:
        """Test QueryRowsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryRowsRequest`
        """
        model = QueryRowsRequest()
        if include_optional:
            return QueryRowsRequest(
                row_sources = [
                    client.models.query_source.QuerySource(
                        root_form_id = '', )
                    ],
                form_id = '',
                columns = [
                    client.models.query_column.QueryColumn(
                        id = '', 
                        formula = '', 
                        expression = '', )
                    ],
                filter = '',
                filter_sets = [
                    client.models.query_filter_set.QueryFilterSet(
                        column_formula = '', 
                        values = [
                            ''
                            ], )
                    ],
                sort = [
                    client.models.query_sort.QuerySort(
                        formula = '', 
                        dir = 'ASC', )
                    ],
                truncate_strings = True,
                validation = { },
                drafts = '',
                tags = [
                    ''
                    ]
            )
        else:
            return QueryRowsRequest(
                row_sources = [
                    client.models.query_source.QuerySource(
                        root_form_id = '', )
                    ],
                columns = [
                    client.models.query_column.QueryColumn(
                        id = '', 
                        formula = '', 
                        expression = '', )
                    ],
        )
        """

    def testQueryRowsRequest(self):
        """Test QueryRowsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
