# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.database_resource import DatabaseResource

class TestDatabaseResource(unittest.TestCase):
    """DatabaseResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseResource:
        """Test DatabaseResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseResource`
        """
        model = DatabaseResource()
        if include_optional:
            return DatabaseResource(
                id = '',
                type = 'DATABASE',
                parent_id = '',
                label = '',
                visibility = '',
                icon = ''
            )
        else:
            return DatabaseResource(
                id = '',
        )
        """

    def testDatabaseResource(self):
        """Test DatabaseResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
