# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.user_preflight_response import UserPreflightResponse

class TestUserPreflightResponse(unittest.TestCase):
    """UserPreflightResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserPreflightResponse:
        """Test UserPreflightResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserPreflightResponse`
        """
        model = UserPreflightResponse()
        if include_optional:
            return UserPreflightResponse(
                user_id = '',
                activation_status = 'NO_ACCOUNT',
                name = '',
                added_to_database = True,
                valid_email = True,
                localized_error_message = ''
            )
        else:
            return UserPreflightResponse(
                activation_status = 'NO_ACCOUNT',
                added_to_database = True,
                valid_email = True,
        )
        """

    def testUserPreflightResponse(self):
        """Test UserPreflightResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
