# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.update_translations_request import UpdateTranslationsRequest

class TestUpdateTranslationsRequest(unittest.TestCase):
    """UpdateTranslationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTranslationsRequest:
        """Test UpdateTranslationsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTranslationsRequest`
        """
        model = UpdateTranslationsRequest()
        if include_optional:
            return UpdateTranslationsRequest(
                strings = [
                    client.models.translation_string.TranslationString(
                        id = '', 
                        original = '', 
                        translated = '', 
                        auto_translated = True, )
                    ]
            )
        else:
            return UpdateTranslationsRequest(
                strings = [
                    client.models.translation_string.TranslationString(
                        id = '', 
                        original = '', 
                        translated = '', 
                        auto_translated = True, )
                    ],
        )
        """

    def testUpdateTranslationsRequest(self):
        """Test UpdateTranslationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
