# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.translation_dictionary import TranslationDictionary

class TestTranslationDictionary(unittest.TestCase):
    """TranslationDictionary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranslationDictionary:
        """Test TranslationDictionary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranslationDictionary`
        """
        model = TranslationDictionary()
        if include_optional:
            return TranslationDictionary(
                id = client.models.translation_dictionary_id.TranslationDictionaryId(
                    database_id = '', 
                    dictionary_id = '', ),
                version = 56,
                language = '',
                translated_strings = [
                    client.models.translation_string.TranslationString(
                        id = '', 
                        original = '', 
                        translated = '', 
                        auto_translated = True, )
                    ]
            )
        else:
            return TranslationDictionary(
                id = client.models.translation_dictionary_id.TranslationDictionaryId(
                    database_id = '', 
                    dictionary_id = '', ),
                version = 56,
                language = '',
                translated_strings = [
                    client.models.translation_string.TranslationString(
                        id = '', 
                        original = '', 
                        translated = '', 
                        auto_translated = True, )
                    ],
        )
        """

    def testTranslationDictionary(self):
        """Test TranslationDictionary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
