# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.form_schema import FormSchema

class TestFormSchema(unittest.TestCase):
    """FormSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormSchema:
        """Test FormSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormSchema`
        """
        model = FormSchema()
        if include_optional:
            return FormSchema(
                id = '',
                label = '',
                schema_version = 56,
                database_id = '',
                parent_form_id = '',
                record_label_field_id = '',
                elements = [
                    client.models.form_schema_element.FormSchemaElement(
                        id = '', 
                        code = '', 
                        label = '', 
                        description = '', 
                        relevance_condition = '', 
                        validation_condition = '', 
                        data_entry_visible = True, 
                        table_visible = True, 
                        required = True, 
                        key = True, 
                        unique = True, 
                        read_only = True, 
                        default_value = '', 
                        default_value_formula = '', 
                        type = '', 
                        security_category_id = '', 
                        type_parameters = null, )
                    ]
            )
        else:
            return FormSchema(
                id = '',
                label = '',
                schema_version = 56,
                database_id = '',
                elements = [
                    client.models.form_schema_element.FormSchemaElement(
                        id = '', 
                        code = '', 
                        label = '', 
                        description = '', 
                        relevance_condition = '', 
                        validation_condition = '', 
                        data_entry_visible = True, 
                        table_visible = True, 
                        required = True, 
                        key = True, 
                        unique = True, 
                        read_only = True, 
                        default_value = '', 
                        default_value_formula = '', 
                        type = '', 
                        security_category_id = '', 
                        type_parameters = null, )
                    ],
        )
        """

    def testFormSchema(self):
        """Test FormSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
