# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.form import Form

class TestForm(unittest.TestCase):
    """Form unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Form:
        """Test Form
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Form`
        """
        model = Form()
        if include_optional:
            return Form(
                id = '',
                var_schema = client.models.form_schema.FormSchema(
                    id = '', 
                    label = '', 
                    schema_version = 56, 
                    database_id = '', 
                    parent_form_id = '', 
                    record_label_field_id = '', 
                    elements = [
                        client.models.form_schema_element.FormSchemaElement(
                            id = '', 
                            code = '', 
                            label = '', 
                            description = '', 
                            relevance_condition = '', 
                            validation_condition = '', 
                            data_entry_visible = True, 
                            table_visible = True, 
                            required = True, 
                            key = True, 
                            unique = True, 
                            read_only = True, 
                            default_value = '', 
                            default_value_formula = '', 
                            type = '', 
                            security_category_id = '', 
                            type_parameters = null, )
                        ], ),
                schema_version = 56,
                permissions = client.models.form_permissions.FormPermissions(
                    view = True, 
                    view_filter = '', 
                    create_record = True, 
                    create_filter = '', 
                    edit_record = True, 
                    edit_filter = '', 
                    delete_record = True, 
                    delete_filter = '', 
                    bulk_delete = True, 
                    export_records = True, 
                    resolve_duplicates = True, 
                    manage_import_configs = True, 
                    update_schema = True, 
                    collection_links = True, 
                    public_form = True, 
                    api = True, 
                    security_categories = [
                        ''
                        ], 
                    locks = [
                        client.models.database_lock.DatabaseLock(
                            id = '', 
                            label = '', 
                            resource_id = '', 
                            date_range = null, 
                            formula = '', 
                            message = '', 
                            deactivated = True, )
                        ], 
                    field_level_conditions = [
                        client.models.field_condition.FieldCondition(
                            operations = [
                                ''
                                ], 
                            criteria = 'ALL', 
                            rules = [
                                client.models.field_condition_rule.FieldConditionRule(
                                    object_type = '', 
                                    predicate_type = '', 
                                    value = '', )
                                ], )
                        ], ),
                visible = True,
                deleted = True,
                suspended = True
            )
        else:
            return Form(
                id = '',
                var_schema = client.models.form_schema.FormSchema(
                    id = '', 
                    label = '', 
                    schema_version = 56, 
                    database_id = '', 
                    parent_form_id = '', 
                    record_label_field_id = '', 
                    elements = [
                        client.models.form_schema_element.FormSchemaElement(
                            id = '', 
                            code = '', 
                            label = '', 
                            description = '', 
                            relevance_condition = '', 
                            validation_condition = '', 
                            data_entry_visible = True, 
                            table_visible = True, 
                            required = True, 
                            key = True, 
                            unique = True, 
                            read_only = True, 
                            default_value = '', 
                            default_value_formula = '', 
                            type = '', 
                            security_category_id = '', 
                            type_parameters = null, )
                        ], ),
                schema_version = 56,
                permissions = client.models.form_permissions.FormPermissions(
                    view = True, 
                    view_filter = '', 
                    create_record = True, 
                    create_filter = '', 
                    edit_record = True, 
                    edit_filter = '', 
                    delete_record = True, 
                    delete_filter = '', 
                    bulk_delete = True, 
                    export_records = True, 
                    resolve_duplicates = True, 
                    manage_import_configs = True, 
                    update_schema = True, 
                    collection_links = True, 
                    public_form = True, 
                    api = True, 
                    security_categories = [
                        ''
                        ], 
                    locks = [
                        client.models.database_lock.DatabaseLock(
                            id = '', 
                            label = '', 
                            resource_id = '', 
                            date_range = null, 
                            formula = '', 
                            message = '', 
                            deactivated = True, )
                        ], 
                    field_level_conditions = [
                        client.models.field_condition.FieldCondition(
                            operations = [
                                ''
                                ], 
                            criteria = 'ALL', 
                            rules = [
                                client.models.field_condition_rule.FieldConditionRule(
                                    object_type = '', 
                                    predicate_type = '', 
                                    value = '', )
                                ], )
                        ], ),
        )
        """

    def testForm(self):
        """Test Form"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
