# coding: utf-8

"""
    ActivityInfo API

    OpenAPI schema generated from AIS CLI api folder

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.get_databases_response import GetDatabasesResponse

class TestGetDatabasesResponse(unittest.TestCase):
    """GetDatabasesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDatabasesResponse:
        """Test GetDatabasesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDatabasesResponse`
        """
        model = GetDatabasesResponse()
        if include_optional:
            return GetDatabasesResponse(
                database_id = '',
                label = '',
                description = '',
                owner_id = '',
                billing_account_id = 56,
                suspended = True,
                published_template = True,
                languages = [
                    ''
                    ]
            )
        else:
            return GetDatabasesResponse(
                database_id = '',
                label = '',
        )
        """

    def testGetDatabasesResponse(self):
        """Test GetDatabasesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
